name = "Parareal"
uuid = "964e4d13-8dbc-4c93-b7e8-f77004e5b2a3"
authors = ["nondairyneutrino <nathaniel.chapman@cwu.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
